### PR TITLE
Added LG parser

### PR DESCRIPTION
**Pull request by prog900**

### CODE REVIEW

**Comment by rvignav** [comment]
If `equals`, `connects`, `replaceNull`, and other such functions in `Parser.java` are the exact same as in `Generator.java`, would it make more sense to call those functions directly from Generator? Or make some such `Utility.java` class that hosts all these functions, so that code is not repeated in several different files?

Otherwise, looks great to me!

**Comment by akolonin** [comment]
Regarding the comment from @rvignav above.
@jenka2014 - should we make the changes suggested by @rvignav before merging the PR or let them be done in separate commit/PR by @rvignav when he starts refactoring the Generator and Segment?

**Comment by prog900** [comment]
> If `equals`, `connects`, `replaceNull`, and other such functions in `Parser.java` are the exact same as in `Generator.java`, would it make more sense to call those functions directly from Generator? Or make some such `Utility.java` class that hosts all these functions, so that code is not repeated in several different files?
> 
> Otherwise, looks great to me!

1. 'equals' and 'Replace null' i got from Segment without any changes and 3 small functions for text processing.
2. 'connects' is modified. I created version 'connects(Word left, Word right)' cause Segment and Generator have no this version. (With Word-Word parameters, only String-String)

**Comment by prog900** [comment]
> Regarding the comment from @rvignav above.
> @jenka2014 - should we make the changes suggested by @rvignav before merging the PR or let them be done in separate commit/PR by @rvignav when he starts refactoring the Generator and Segment?

I think we need to create a separate module for Utility functions. that used in Generator, Segment and Parser. But it should be done after refactoring Segment and Generator. Because all functions have to be consistent

**Pull request merged**
