### PR TITLE
Finish task 2.4 & 2.5

### PR DESCRIPTION
**Pull request by rvignav**
2.4. Implement full-blown version of LG loader capable to parse English grammar https://github.com/opencog/link-grammar/blob/master/data/en/4.0.dict (including support for "macros" like "`<post-nominal-u>`"); - DONE
2.5. Add a unit test for full-blown version of LG loader capable to parse English grammar involving parse of the same sentences that we used in 2.3, but relying on complete English LG.

### CODE REVIEW

**Comment by akolonin** [comment]
Need changes:

1) In src/org/aigents/nlp/gen I see files:
dict_30C_2018-12-31_0006.4.0.dict
poc_english.txt
- they should be in a separate folder called test, like in "src/org/aigents/nlp/gen/test" or even "/test" at the root.
Ideally, we should have a proper organization of Java project (with separate roots for test and main) but at least we need to keep test and data files away from the sources.

2) In src/org/aigents/nlp/lg I see two dict and text filed - why do you need them if you have the files above? Can we use single file for tests like discussed above?  

3) Follow structure of https://github.com/opencog/link-grammar/
- have "/data/lg" folder at the root 
- have "https://github.com/opencog/link-grammar/tree/master/data/en" in "/data/lg/en"
- have "https://github.com/opencog/link-grammar/tree/master/data/ru" in "/data/lg/ru"

4) Make the project structure compliant to "best practices"
```
src
  main
    java
      org
         aigents
             nlp
                gen
                lg
                sat
  test
    java 
      org
         aigents
             nlp
                gen
                lg
                sat
data
  lg
    en
    ru
```

5) Add completion of 2.5 to the PR

6) Add completion of 2.6 to the PR - try to load /data/lg/ru - make sure if it works, fix if there are problems that can be fixed easily, create an issue of there are problems that need investigation

7) Update readme in the root respectively to the above.

Let's discuss on the call...

**Comment by rvignav** [comment]
Hi @akolonin, here are the final results. Please let me know if you can merge now!
IMAGE 2020-07-26 13:01:31

**Comment by rvignav** [comment]
Hi @akolonin, here are the following results. Please let me know if you can now merge this PR.
Screen Shot 2020-07-26 at 5 46 42 PM

**Comment by rvignav** [comment]
Hi @akolonin, here are the following results. Please let me know if you can now merge this PR.
Screen Shot 2020-07-26 at 5 56 36 PM

**Comment by rvignav** [comment]
Hi @akolonin, here are the following results. Please let me know if you can now merge this PR.
Screen Shot 2020-07-26 at 5 56 36 PM

**Pull request merged**
